spring:
  application:
    name: UniRent

  datasource:
    url: jdbc:postgresql://postgres:5432/UniRent
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888 # Replace with your issuer URI
          jwk-set-uri: http://localhost:8888/.well-known/jwks.json # Replace with your JWK Set URI

# JWT Configuration
jwt:
  secret: aGi45u87K34m/25Cnmm0Ppuu31Lc7/Gb+tFbZQxkXSs=
  expiration: 86400000


logging:
  level:
    org.springframework.security: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Server Configuration
server:
  port: 8888
