spring:
  application:
    name: UniRent

  datasource:
    url: jdbc:postgresql://postgres:5432/UniRent
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888
          jwk-set-uri: http://localhost:8888/.well-known/jwks.json

# JWT Configuration
jwt:
  secret: aGi45u87K34m/25Cnmm0Ppuu31Lc7/Gb+tFbZQxkXSs=
  expirationMs: 86400000

# Stripe Configuration
stripe:
  secret-key: sk_test_51R544ORu3YBYxBYKbSvdvLG14OoWNKUyOOCF9gt9Xndlx2hzzoauj054S76y3IwN5Yt7o3gV0Y0MBThfEvDmWrpe00y7Ywrpqq

logging:
  level:
    org.springframework.security: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Server Configuration
server:
  port: 8888
